/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandardsRouteImport } from './routes/standards'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegistersRouteImport } from './routes/registers'
import { Route as MetrologyRouteImport } from './routes/metrology'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as AppealsStatusRouteImport } from './routes/appeals-status'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const StandardsRoute = StandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersRoute = RegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const MetrologyRoute = MetrologyRouteImport.update({
  id: '/metrology',
  path: '/metrology',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsStatusRoute = AppealsStatusRouteImport.update({
  id: '/appeals-status',
  path: '/appeals-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeals': typeof AppealsRoute
  '/appeals-status': typeof AppealsStatusRoute
  '/certification': typeof CertificationRoute
  '/metrology': typeof MetrologyRoute
  '/registers': typeof RegistersRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeals': typeof AppealsRoute
  '/appeals-status': typeof AppealsStatusRoute
  '/certification': typeof CertificationRoute
  '/metrology': typeof MetrologyRoute
  '/registers': typeof RegistersRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appeals': typeof AppealsRoute
  '/appeals-status': typeof AppealsStatusRoute
  '/certification': typeof CertificationRoute
  '/metrology': typeof MetrologyRoute
  '/registers': typeof RegistersRoute
  '/services': typeof ServicesRoute
  '/standards': typeof StandardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/appeals'
    | '/appeals-status'
    | '/certification'
    | '/metrology'
    | '/registers'
    | '/services'
    | '/standards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appeals'
    | '/appeals-status'
    | '/certification'
    | '/metrology'
    | '/registers'
    | '/services'
    | '/standards'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/appeals'
    | '/appeals-status'
    | '/certification'
    | '/metrology'
    | '/registers'
    | '/services'
    | '/standards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppealsRoute: typeof AppealsRoute
  AppealsStatusRoute: typeof AppealsStatusRoute
  CertificationRoute: typeof CertificationRoute
  MetrologyRoute: typeof MetrologyRoute
  RegistersRoute: typeof RegistersRoute
  ServicesRoute: typeof ServicesRoute
  StandardsRoute: typeof StandardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standards': {
      id: '/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof StandardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers': {
      id: '/registers'
      path: '/registers'
      fullPath: '/registers'
      preLoaderRoute: typeof RegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrology': {
      id: '/metrology'
      path: '/metrology'
      fullPath: '/metrology'
      preLoaderRoute: typeof MetrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals-status': {
      id: '/appeals-status'
      path: '/appeals-status'
      fullPath: '/appeals-status'
      preLoaderRoute: typeof AppealsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppealsRoute: AppealsRoute,
  AppealsStatusRoute: AppealsStatusRoute,
  CertificationRoute: CertificationRoute,
  MetrologyRoute: MetrologyRoute,
  RegistersRoute: RegistersRoute,
  ServicesRoute: ServicesRoute,
  StandardsRoute: StandardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
